image: node:14

stages:
  - install
  - test
  - build

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install

test:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/
